# Generated by Django 6.0.7 on 2026-07-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="preview_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="blog/", verbose_name="Превью"
            ),
        ),
    ]
