# Generated by Django 6.0.6 on 2026-06-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="catalog/", verbose_name="Изображение"
            ),
        ),
    ]
